const locale: Record<string, Record<string, string>> = {
	es: {
		'title.one': 'Sobre',
		'title.two': 'Nosotros',
		'company.name': 'Altiore-Fiducia',
		'paragraph.one':
			'es un corredor de reaseguros que ayuda a sus clientes a manejar sus riesgos, proteger sus bienes y recuperar sus pérdidas, mediante este servicio ayudamos a que los negocios e instituciones se mantengan operando y reconstruyan sus activos.',
		'paragraph.two':
			'nace de la necesidad de los constantes cambios que surgen alrededor del mundo y las fuertes incertidumbres generadas por las tomas de riesgos por parte de las empresas en ser respaldadas en todo momento de manera ágil.',
		'paragraph.three.one': 'Su nombre significa',
		'paragraph.three.two': 'Alta Confianza/Confianza Más Alta',
		'paragraph.three.three':
			'en latín, lo cual proyecto lo que queremos brindar a todos quienes lleguen a nosotros mediante las coberturas de reaseguros de calidad de respaldo (security) de excelente prestigio a nivel mundial y eficiente gestión de riesgos.',
	},
	en: {
		'title.one': 'About',
		'title.two': 'Us',
		'company.name': 'Altiore-Fiducia',
		'paragraph.one':
			'is a reinsurance broker that helps its clients manage their risks, protect their assets, and recover their losses. Through this service, we help businesses and institutions keep operating and rebuild their assets.',
		'paragraph.two':
			'was born from the need for constant changes that occur around the world and the strong uncertainties generated by the risk-taking of companies to be backed at all times in an agile manner.',
		'paragraph.three.one': 'Its name means',
		'paragraph.three.two': 'High Trust/Higher Trust',
		'paragraph.three.three':
			'in Latin, which projects what we want to provide to all those who come to us through reinsurance coverages of quality backing (security) with excellent worldwide prestige and efficient risk management.',
	},
};

export default locale;
